// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: console_messages.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertConsoleMessage = `-- name: InsertConsoleMessage :exec
INSERT INTO console_messages (instance_id, log_time, severity, log_msg, mqtt_timestamp)
VALUES ($1, $2, $3, $4, $5)
`

type InsertConsoleMessageParams struct {
	InstanceID    *string
	LogTime       pgtype.Timestamptz
	Severity      *string
	LogMsg        *string
	MqttTimestamp pgtype.Timestamptz
}

func (q *Queries) InsertConsoleMessage(ctx context.Context, arg InsertConsoleMessageParams) error {
	_, err := q.db.Exec(ctx, insertConsoleMessage,
		arg.InstanceID,
		arg.LogTime,
		arg.Severity,
		arg.LogMsg,
		arg.MqttTimestamp,
	)
	return err
}
