// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcdb

import (
	"context"
)

// iteratorForInsertCallFrequencies implements pgx.CopyFromSource.
type iteratorForInsertCallFrequencies struct {
	rows                 []InsertCallFrequenciesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCallFrequencies) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCallFrequencies) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CallID,
		r.rows[0].CallStartTime,
		r.rows[0].Freq,
		r.rows[0].Time,
		r.rows[0].Pos,
		r.rows[0].Len,
		r.rows[0].ErrorCount,
		r.rows[0].SpikeCount,
	}, nil
}

func (r iteratorForInsertCallFrequencies) Err() error {
	return nil
}

func (q *Queries) InsertCallFrequencies(ctx context.Context, arg []InsertCallFrequenciesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"call_frequencies"}, []string{"call_id", "call_start_time", "freq", "time", "pos", "len", "error_count", "spike_count"}, &iteratorForInsertCallFrequencies{rows: arg})
}

// iteratorForInsertCallTransmissions implements pgx.CopyFromSource.
type iteratorForInsertCallTransmissions struct {
	rows                 []InsertCallTransmissionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCallTransmissions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCallTransmissions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CallID,
		r.rows[0].CallStartTime,
		r.rows[0].Src,
		r.rows[0].Time,
		r.rows[0].Pos,
		r.rows[0].Duration,
		r.rows[0].Emergency,
		r.rows[0].SignalSystem,
		r.rows[0].Tag,
	}, nil
}

func (r iteratorForInsertCallTransmissions) Err() error {
	return nil
}

func (q *Queries) InsertCallTransmissions(ctx context.Context, arg []InsertCallTransmissionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"call_transmissions"}, []string{"call_id", "call_start_time", "src", "time", "pos", "duration", "emergency", "signal_system", "tag"}, &iteratorForInsertCallTransmissions{rows: arg})
}

// iteratorForInsertDecodeRates implements pgx.CopyFromSource.
type iteratorForInsertDecodeRates struct {
	rows                 []InsertDecodeRatesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDecodeRates) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDecodeRates) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SystemID,
		r.rows[0].DecodeRate,
		r.rows[0].DecodeRateInterval,
		r.rows[0].ControlChannel,
		r.rows[0].SysNum,
		r.rows[0].SysName,
		r.rows[0].Time,
		r.rows[0].InstanceID,
	}, nil
}

func (r iteratorForInsertDecodeRates) Err() error {
	return nil
}

func (q *Queries) InsertDecodeRates(ctx context.Context, arg []InsertDecodeRatesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"decode_rates"}, []string{"system_id", "decode_rate", "decode_rate_interval", "control_channel", "sys_num", "sys_name", "time", "instance_id"}, &iteratorForInsertDecodeRates{rows: arg})
}

// iteratorForInsertRawMessages implements pgx.CopyFromSource.
type iteratorForInsertRawMessages struct {
	rows                 []InsertRawMessagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRawMessages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRawMessages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Topic,
		r.rows[0].Payload,
		r.rows[0].ReceivedAt,
		r.rows[0].InstanceID,
	}, nil
}

func (r iteratorForInsertRawMessages) Err() error {
	return nil
}

func (q *Queries) InsertRawMessages(ctx context.Context, arg []InsertRawMessagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"mqtt_raw_messages"}, []string{"topic", "payload", "received_at", "instance_id"}, &iteratorForInsertRawMessages{rows: arg})
}

// iteratorForInsertRecorderSnapshots implements pgx.CopyFromSource.
type iteratorForInsertRecorderSnapshots struct {
	rows                 []InsertRecorderSnapshotsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRecorderSnapshots) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRecorderSnapshots) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].InstanceID,
		r.rows[0].RecorderID,
		r.rows[0].SrcNum,
		r.rows[0].RecNum,
		r.rows[0].Type,
		r.rows[0].RecState,
		r.rows[0].RecStateType,
		r.rows[0].Freq,
		r.rows[0].Duration,
		r.rows[0].Count,
		r.rows[0].Squelched,
		r.rows[0].Time,
	}, nil
}

func (r iteratorForInsertRecorderSnapshots) Err() error {
	return nil
}

func (q *Queries) InsertRecorderSnapshots(ctx context.Context, arg []InsertRecorderSnapshotsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recorder_snapshots"}, []string{"instance_id", "recorder_id", "src_num", "rec_num", "type", "rec_state", "rec_state_type", "freq", "duration", "count", "squelched", "time"}, &iteratorForInsertRecorderSnapshots{rows: arg})
}

// iteratorForInsertTrunkingMessages implements pgx.CopyFromSource.
type iteratorForInsertTrunkingMessages struct {
	rows                 []InsertTrunkingMessagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTrunkingMessages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTrunkingMessages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SystemID,
		r.rows[0].SysNum,
		r.rows[0].SysName,
		r.rows[0].TrunkMsg,
		r.rows[0].TrunkMsgType,
		r.rows[0].Opcode,
		r.rows[0].OpcodeType,
		r.rows[0].OpcodeDesc,
		r.rows[0].Meta,
		r.rows[0].Time,
		r.rows[0].InstanceID,
	}, nil
}

func (r iteratorForInsertTrunkingMessages) Err() error {
	return nil
}

func (q *Queries) InsertTrunkingMessages(ctx context.Context, arg []InsertTrunkingMessagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"trunking_messages"}, []string{"system_id", "sys_num", "sys_name", "trunk_msg", "trunk_msg_type", "opcode", "opcode_type", "opcode_desc", "meta", "time", "instance_id"}, &iteratorForInsertTrunkingMessages{rows: arg})
}
