// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instances.sql

package sqlcdb

import (
	"context"
)

const upsertInstance = `-- name: UpsertInstance :one
INSERT INTO instances (instance_id, first_seen, last_seen)
VALUES ($1, now(), now())
ON CONFLICT (instance_id) DO UPDATE
    SET last_seen = now()
RETURNING id
`

func (q *Queries) UpsertInstance(ctx context.Context, instanceID string) (int, error) {
	row := q.db.QueryRow(ctx, upsertInstance, instanceID)
	var id int
	err := row.Scan(&id)
	return id, err
}
