// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_configs.sql

package sqlcdb

import (
	"context"
)

const insertInstanceConfig = `-- name: InsertInstanceConfig :exec
INSERT INTO instance_configs (instance_id, capture_dir, upload_server, call_timeout, log_file, instance_key, config_json, "time")
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
`

type InsertInstanceConfigParams struct {
	InstanceID   *string
	CaptureDir   *string
	UploadServer *string
	CallTimeout  *float32
	LogFile      *string
	InstanceKey  *string
	ConfigJson   []byte
}

func (q *Queries) InsertInstanceConfig(ctx context.Context, arg InsertInstanceConfigParams) error {
	_, err := q.db.Exec(ctx, insertInstanceConfig,
		arg.InstanceID,
		arg.CaptureDir,
		arg.UploadServer,
		arg.CallTimeout,
		arg.LogFile,
		arg.InstanceKey,
		arg.ConfigJson,
	)
	return err
}
