// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugin_statuses.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPluginStatus = `-- name: InsertPluginStatus :exec
INSERT INTO plugin_statuses (client_id, instance_id, status, "time")
VALUES ($1, $2, $3, $4)
`

type InsertPluginStatusParams struct {
	ClientID   *string
	InstanceID *string
	Status     *string
	Time       pgtype.Timestamptz
}

func (q *Queries) InsertPluginStatus(ctx context.Context, arg InsertPluginStatusParams) error {
	_, err := q.db.Exec(ctx, insertPluginStatus,
		arg.ClientID,
		arg.InstanceID,
		arg.Status,
		arg.Time,
	)
	return err
}
