// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_messages.sql

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertRawMessagesParams struct {
	Topic      string
	Payload    []byte
	ReceivedAt pgtype.Timestamptz
	InstanceID *string
}
