// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recorders.sql

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertDecodeRatesParams struct {
	SystemID           *int32
	DecodeRate         *float32
	DecodeRateInterval *float32
	ControlChannel     *int64
	SysNum             *int16
	SysName            *string
	Time               pgtype.Timestamptz
	InstanceID         *string
}

type InsertRecorderSnapshotsParams struct {
	InstanceID   *string
	RecorderID   *string
	SrcNum       *int16
	RecNum       *int16
	Type         *string
	RecState     *int16
	RecStateType *string
	Freq         *int64
	Duration     *float32
	Count        *int32
	Squelched    *bool
	Time         pgtype.Timestamptz
}
