// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package sqlcdb

import (
	"context"
)

const findOrCreateSite = `-- name: FindOrCreateSite :one
INSERT INTO sites (system_id, instance_id, short_name, first_seen, last_seen)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (instance_id, short_name) DO UPDATE
    SET last_seen = now()
RETURNING site_id
`

type FindOrCreateSiteParams struct {
	SystemID   int
	InstanceID string
	ShortName  string
}

func (q *Queries) FindOrCreateSite(ctx context.Context, arg FindOrCreateSiteParams) (int, error) {
	row := q.db.QueryRow(ctx, findOrCreateSite, arg.SystemID, arg.InstanceID, arg.ShortName)
	var site_id int
	err := row.Scan(&site_id)
	return site_id, err
}

const getSiteByID = `-- name: GetSiteByID :one
SELECT site_id, system_id, short_name, instance_id,
    COALESCE(nac, '') AS nac, rfss, p25_site_id, sys_num
FROM sites WHERE site_id = $1
`

type GetSiteByIDRow struct {
	SiteID     int
	SystemID   int
	ShortName  string
	InstanceID string
	Nac        string
	Rfss       *int16
	P25SiteID  *int16
	SysNum     *int16
}

func (q *Queries) GetSiteByID(ctx context.Context, siteID int) (GetSiteByIDRow, error) {
	row := q.db.QueryRow(ctx, getSiteByID, siteID)
	var i GetSiteByIDRow
	err := row.Scan(
		&i.SiteID,
		&i.SystemID,
		&i.ShortName,
		&i.InstanceID,
		&i.Nac,
		&i.Rfss,
		&i.P25SiteID,
		&i.SysNum,
	)
	return i, err
}

const listSitesForSystem = `-- name: ListSitesForSystem :many
SELECT site_id, system_id, short_name, instance_id,
    COALESCE(nac, '') AS nac, rfss, p25_site_id, sys_num
FROM sites WHERE system_id = $1
ORDER BY site_id
`

type ListSitesForSystemRow struct {
	SiteID     int
	SystemID   int
	ShortName  string
	InstanceID string
	Nac        string
	Rfss       *int16
	P25SiteID  *int16
	SysNum     *int16
}

func (q *Queries) ListSitesForSystem(ctx context.Context, systemID int) ([]ListSitesForSystemRow, error) {
	rows, err := q.db.Query(ctx, listSitesForSystem, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSitesForSystemRow{}
	for rows.Next() {
		var i ListSitesForSystemRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SystemID,
			&i.ShortName,
			&i.InstanceID,
			&i.Nac,
			&i.Rfss,
			&i.P25SiteID,
			&i.SysNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAllSites = `-- name: LoadAllSites :many
SELECT s.site_id, s.system_id, s.instance_id, s.short_name, COALESCE(sys.sysid, '') AS sysid
FROM sites s
JOIN systems sys ON sys.system_id = s.system_id
`

type LoadAllSitesRow struct {
	SiteID     int
	SystemID   int
	InstanceID string
	ShortName  string
	Sysid      string
}

func (q *Queries) LoadAllSites(ctx context.Context) ([]LoadAllSitesRow, error) {
	rows, err := q.db.Query(ctx, loadAllSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadAllSitesRow{}
	for rows.Next() {
		var i LoadAllSitesRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SystemID,
			&i.InstanceID,
			&i.ShortName,
			&i.Sysid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAllSitesAPI = `-- name: LoadAllSitesAPI :many
SELECT site_id, system_id, short_name, instance_id,
    COALESCE(nac, '') AS nac, rfss, p25_site_id, sys_num
FROM sites ORDER BY site_id
`

type LoadAllSitesAPIRow struct {
	SiteID     int
	SystemID   int
	ShortName  string
	InstanceID string
	Nac        string
	Rfss       *int16
	P25SiteID  *int16
	SysNum     *int16
}

func (q *Queries) LoadAllSitesAPI(ctx context.Context) ([]LoadAllSitesAPIRow, error) {
	rows, err := q.db.Query(ctx, loadAllSitesAPI)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadAllSitesAPIRow{}
	for rows.Next() {
		var i LoadAllSitesAPIRow
		if err := rows.Scan(
			&i.SiteID,
			&i.SystemID,
			&i.ShortName,
			&i.InstanceID,
			&i.Nac,
			&i.Rfss,
			&i.P25SiteID,
			&i.SysNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const siteExists = `-- name: SiteExists :one
SELECT EXISTS(SELECT 1 FROM sites WHERE site_id = $1)
`

func (q *Queries) SiteExists(ctx context.Context, siteID int) (bool, error) {
	row := q.db.QueryRow(ctx, siteExists, siteID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSite = `-- name: UpdateSite :exec
UPDATE sites SET
    sys_num         = CASE WHEN $1::smallint > 0 THEN $1 ELSE sys_num END,
    nac             = CASE WHEN $2::text <> '' AND $2 <> '0' THEN $2 ELSE nac END,
    rfss            = CASE WHEN $3::smallint > 0 THEN $3 ELSE rfss END,
    p25_site_id     = CASE WHEN $4::smallint > 0 THEN $4 ELSE p25_site_id END,
    system_type_raw = COALESCE(NULLIF($5::text, ''), system_type_raw),
    updated_at      = now()
WHERE site_id = $6
`

type UpdateSiteParams struct {
	SysNum        int16
	Nac           string
	Rfss          int16
	P25SiteID     int16
	SystemTypeRaw string
	SiteID        int
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) error {
	_, err := q.db.Exec(ctx, updateSite,
		arg.SysNum,
		arg.Nac,
		arg.Rfss,
		arg.P25SiteID,
		arg.SystemTypeRaw,
		arg.SiteID,
	)
	return err
}

const updateSiteFields = `-- name: UpdateSiteFields :exec
UPDATE sites SET
    short_name  = CASE WHEN $1::text <> '' THEN $1 ELSE short_name END,
    instance_id = CASE WHEN $2::text <> '' THEN $2 ELSE instance_id END,
    nac         = CASE WHEN $3::text <> '' THEN $3 ELSE nac END,
    rfss        = CASE WHEN $4::smallint > 0 THEN $4 ELSE rfss END,
    p25_site_id = CASE WHEN $5::smallint > 0 THEN $5 ELSE p25_site_id END
WHERE site_id = $6
`

type UpdateSiteFieldsParams struct {
	ShortName     string
	NewInstanceID string
	Nac           string
	Rfss          int16
	P25SiteID     int16
	SiteID        int
}

func (q *Queries) UpdateSiteFields(ctx context.Context, arg UpdateSiteFieldsParams) error {
	_, err := q.db.Exec(ctx, updateSiteFields,
		arg.ShortName,
		arg.NewInstanceID,
		arg.Nac,
		arg.Rfss,
		arg.P25SiteID,
		arg.SiteID,
	)
	return err
}
