// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlcdb

import (
	"context"
)

const getOverallStats = `-- name: GetOverallStats :one
SELECT
    (SELECT count(*)::int FROM systems WHERE deleted_at IS NULL) AS systems,
    (SELECT count(*)::int FROM talkgroups) AS talkgroups,
    (SELECT count(*)::int FROM units) AS units,
    (SELECT COALESCE(sum(n_live_tup), 0)::int FROM pg_stat_user_tables
     WHERE relname LIKE 'calls_y%') AS total_calls,
    (SELECT count(*)::int FROM calls WHERE start_time > now() - interval '30 days') AS calls_30d,
    (SELECT COALESCE(sum(calls_24h), 0)::int FROM talkgroups) AS calls_24h,
    (SELECT COALESCE(sum(calls_1h), 0)::int FROM talkgroups) AS calls_1h,
    COALESCE((SELECT sum(duration) / 3600.0 FROM calls
     WHERE start_time > now() - interval '30 days' AND duration IS NOT NULL), 0)::float8 AS total_duration_hours
`

type GetOverallStatsRow struct {
	Systems            int
	Talkgroups         int
	Units              int
	TotalCalls         int
	Calls30d           int
	Calls24h           int
	Calls1h            int
	TotalDurationHours float64
}

func (q *Queries) GetOverallStats(ctx context.Context) (GetOverallStatsRow, error) {
	row := q.db.QueryRow(ctx, getOverallStats)
	var i GetOverallStatsRow
	err := row.Scan(
		&i.Systems,
		&i.Talkgroups,
		&i.Units,
		&i.TotalCalls,
		&i.Calls30d,
		&i.Calls24h,
		&i.Calls1h,
		&i.TotalDurationHours,
	)
	return i, err
}

const getSystemActivity = `-- name: GetSystemActivity :many
SELECT
    s.system_id, COALESCE(s.name, '') AS system_name, s.sysid,
    COALESCE((SELECT sum(t.calls_1h) FROM talkgroups t WHERE t.system_id = s.system_id), 0)::int AS calls_1h,
    COALESCE((SELECT sum(t.calls_24h) FROM talkgroups t WHERE t.system_id = s.system_id), 0)::int AS calls_24h,
    (SELECT count(*)::int FROM talkgroups t WHERE t.system_id = s.system_id AND t.calls_1h > 0) AS active_talkgroups,
    COALESCE((SELECT sum(t.unit_count_30d) FROM talkgroups t WHERE t.system_id = s.system_id), 0)::int AS active_units
FROM systems s
WHERE s.deleted_at IS NULL
ORDER BY s.system_id
`

type GetSystemActivityRow struct {
	SystemID         int
	SystemName       string
	Sysid            string
	Calls1h          int
	Calls24h         int
	ActiveTalkgroups int
	ActiveUnits      int
}

func (q *Queries) GetSystemActivity(ctx context.Context) ([]GetSystemActivityRow, error) {
	rows, err := q.db.Query(ctx, getSystemActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSystemActivityRow{}
	for rows.Next() {
		var i GetSystemActivityRow
		if err := rows.Scan(
			&i.SystemID,
			&i.SystemName,
			&i.Sysid,
			&i.Calls1h,
			&i.Calls24h,
			&i.ActiveTalkgroups,
			&i.ActiveUnits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listP25Systems = `-- name: ListP25Systems :many
SELECT s.system_id, COALESCE(s.name, '') AS name, s.sysid, s.wacn,
    (SELECT count(*)::int FROM talkgroups t WHERE t.system_id = s.system_id) AS talkgroup_count,
    (SELECT count(*)::int FROM units u WHERE u.system_id = s.system_id) AS unit_count,
    COALESCE((SELECT sum(t.calls_24h) FROM talkgroups t WHERE t.system_id = s.system_id), 0)::int AS calls_24h
FROM systems s
WHERE s.system_type IN ('p25', 'smartnet') AND s.deleted_at IS NULL
ORDER BY s.system_id
`

type ListP25SystemsRow struct {
	SystemID       int
	Name           string
	Sysid          string
	Wacn           string
	TalkgroupCount int
	UnitCount      int
	Calls24h       int
}

func (q *Queries) ListP25Systems(ctx context.Context) ([]ListP25SystemsRow, error) {
	rows, err := q.db.Query(ctx, listP25Systems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListP25SystemsRow{}
	for rows.Next() {
		var i ListP25SystemsRow
		if err := rows.Scan(
			&i.SystemID,
			&i.Name,
			&i.Sysid,
			&i.Wacn,
			&i.TalkgroupCount,
			&i.UnitCount,
			&i.Calls24h,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
