// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: systems.sql

package sqlcdb

import (
	"context"
)

const createSystem = `-- name: CreateSystem :one
INSERT INTO systems (system_type, name, sysid, wacn)
VALUES ('p25', $1, '0', '0')
RETURNING system_id
`

func (q *Queries) CreateSystem(ctx context.Context, name *string) (int, error) {
	row := q.db.QueryRow(ctx, createSystem, name)
	var system_id int
	err := row.Scan(&system_id)
	return system_id, err
}

const findSystemBySysidWacn = `-- name: FindSystemBySysidWacn :one
SELECT system_id FROM systems
WHERE sysid = $1 AND wacn = $2
  AND sysid <> '0'
  AND system_id <> $3
  AND deleted_at IS NULL
LIMIT 1
`

type FindSystemBySysidWacnParams struct {
	Sysid    string
	Wacn     string
	SystemID int
}

func (q *Queries) FindSystemBySysidWacn(ctx context.Context, arg FindSystemBySysidWacnParams) (int, error) {
	row := q.db.QueryRow(ctx, findSystemBySysidWacn, arg.Sysid, arg.Wacn, arg.SystemID)
	var system_id int
	err := row.Scan(&system_id)
	return system_id, err
}

const findSystemViaSite = `-- name: FindSystemViaSite :one
SELECT s.system_id, COALESCE(sys.sysid, '') AS sysid
FROM sites s
JOIN systems sys ON sys.system_id = s.system_id
WHERE s.instance_id = $1 AND s.short_name = $2
LIMIT 1
`

type FindSystemViaSiteParams struct {
	InstanceID string
	ShortName  string
}

type FindSystemViaSiteRow struct {
	SystemID int
	Sysid    string
}

func (q *Queries) FindSystemViaSite(ctx context.Context, arg FindSystemViaSiteParams) (FindSystemViaSiteRow, error) {
	row := q.db.QueryRow(ctx, findSystemViaSite, arg.InstanceID, arg.ShortName)
	var i FindSystemViaSiteRow
	err := row.Scan(&i.SystemID, &i.Sysid)
	return i, err
}

const getSystemByID = `-- name: GetSystemByID :one
SELECT system_id, system_type, COALESCE(name, '') AS name, sysid, wacn
FROM systems WHERE system_id = $1 AND deleted_at IS NULL
`

type GetSystemByIDRow struct {
	SystemID   int
	SystemType string
	Name       string
	Sysid      string
	Wacn       string
}

func (q *Queries) GetSystemByID(ctx context.Context, systemID int) (GetSystemByIDRow, error) {
	row := q.db.QueryRow(ctx, getSystemByID, systemID)
	var i GetSystemByIDRow
	err := row.Scan(
		&i.SystemID,
		&i.SystemType,
		&i.Name,
		&i.Sysid,
		&i.Wacn,
	)
	return i, err
}

const listActiveSystems = `-- name: ListActiveSystems :many
SELECT system_id, system_type, COALESCE(name, '') AS name, sysid, wacn
FROM systems
WHERE deleted_at IS NULL
ORDER BY system_id
`

type ListActiveSystemsRow struct {
	SystemID   int
	SystemType string
	Name       string
	Sysid      string
	Wacn       string
}

func (q *Queries) ListActiveSystems(ctx context.Context) ([]ListActiveSystemsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSystemsRow{}
	for rows.Next() {
		var i ListActiveSystemsRow
		if err := rows.Scan(
			&i.SystemID,
			&i.SystemType,
			&i.Name,
			&i.Sysid,
			&i.Wacn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadAllSystems = `-- name: LoadAllSystems :many
SELECT system_id, system_type, COALESCE(name, '') AS name, sysid, wacn
FROM systems
WHERE deleted_at IS NULL
`

type LoadAllSystemsRow struct {
	SystemID   int
	SystemType string
	Name       string
	Sysid      string
	Wacn       string
}

func (q *Queries) LoadAllSystems(ctx context.Context) ([]LoadAllSystemsRow, error) {
	rows, err := q.db.Query(ctx, loadAllSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadAllSystemsRow{}
	for rows.Next() {
		var i LoadAllSystemsRow
		if err := rows.Scan(
			&i.SystemID,
			&i.SystemType,
			&i.Name,
			&i.Sysid,
			&i.Wacn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemFields = `-- name: UpdateSystemFields :exec
UPDATE systems SET
    name  = CASE WHEN $1::text <> '' THEN $1 ELSE name END,
    sysid = CASE WHEN $2::text <> '' THEN $2 ELSE sysid END,
    wacn  = CASE WHEN $3::text <> '' THEN $3 ELSE wacn END
WHERE system_id = $4 AND deleted_at IS NULL
`

type UpdateSystemFieldsParams struct {
	Name     string
	Sysid    string
	Wacn     string
	SystemID int
}

func (q *Queries) UpdateSystemFields(ctx context.Context, arg UpdateSystemFieldsParams) error {
	_, err := q.db.Exec(ctx, updateSystemFields,
		arg.Name,
		arg.Sysid,
		arg.Wacn,
		arg.SystemID,
	)
	return err
}

const updateSystemIdentity = `-- name: UpdateSystemIdentity :exec
UPDATE systems SET
    system_type = COALESCE(NULLIF($1::text, ''), system_type),
    sysid       = CASE WHEN $2::text <> '' AND $2 <> '0' THEN $2 ELSE sysid END,
    wacn        = CASE WHEN $3::text <> '' AND $3 <> '0' THEN $3 ELSE wacn END,
    name        = COALESCE(NULLIF($4::text, ''), name)
WHERE system_id = $5 AND deleted_at IS NULL
`

type UpdateSystemIdentityParams struct {
	SystemType string
	Sysid      string
	Wacn       string
	Name       string
	SystemID   int
}

func (q *Queries) UpdateSystemIdentity(ctx context.Context, arg UpdateSystemIdentityParams) error {
	_, err := q.db.Exec(ctx, updateSystemIdentity,
		arg.SystemType,
		arg.Sysid,
		arg.Wacn,
		arg.Name,
		arg.SystemID,
	)
	return err
}
