// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trunking_messages.sql

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertTrunkingMessagesParams struct {
	SystemID     *int32
	SysNum       *int16
	SysName      *string
	TrunkMsg     *int32
	TrunkMsgType *string
	Opcode       *string
	OpcodeType   *string
	OpcodeDesc   *string
	Meta         []byte
	Time         pgtype.Timestamptz
	InstanceID   *string
}
