linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
  disable-all: true

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

issues:
  new-from-rev: HEAD~1
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
