// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/call-groups": {
            "get": {
                "description": "Returns deduplicated call groups (calls from multiple recorders grouped together)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "call-groups"
                ],
                "summary": "List call groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time filter (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CallGroupListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/call-groups/{id}": {
            "get": {
                "description": "Returns a call group with all its individual call recordings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "call-groups"
                ],
                "summary": "Get a call group",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Call group ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CallGroupDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls": {
            "get": {
                "description": "Returns call recordings with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "List all calls",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by system ID",
                        "name": "system",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by talkgroup ID",
                        "name": "talkgroup",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time filter (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CallListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/active": {
            "get": {
                "description": "Returns currently active calls (calls without a stop_time)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "List active calls",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID or short_name",
                        "name": "system",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "System short name",
                        "name": "sys_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by talkgroup ID",
                        "name": "talkgroup",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by emergency status",
                        "name": "emergency",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by encryption status",
                        "name": "encrypted",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CallListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/active/realtime": {
            "get": {
                "description": "Returns currently active calls from in-memory tracker (real-time from MQTT)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get real-time active calls",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/calls/recent": {
            "get": {
                "description": "Returns recently completed calls from database with full unit list and audio status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get recently ended calls",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of calls to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/calls/{id}": {
            "get": {
                "description": "Returns a single call by its trunk-recorder call ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get a call",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trunk-recorder call ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Call"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/{id}/audio": {
            "get": {
                "description": "Streams the audio file for a call",
                "produces": [
                    "audio/mpeg",
                    "audio/mp4",
                    "audio/wav",
                    "audio/ogg"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get call audio",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trunk-recorder call ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/{id}/frequencies": {
            "get": {
                "description": "Returns the list of frequency entries (freqList) within a call, ordered by position in the audio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get call frequencies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trunk-recorder call ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response with frequencies array and count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/{id}/transcribe": {
            "post": {
                "description": "Queues a call for transcription (or re-transcription)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Queue call for transcription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Call ID (tr_call_id or numeric ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request body",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/rest.TranscribeCallRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/{id}/transcription": {
            "get": {
                "description": "Returns the transcription for a specific call",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get call transcription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Call ID (tr_call_id or numeric ID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Transcription"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calls/{id}/transmissions": {
            "get": {
                "description": "Returns the list of unit transmissions (srcList) within a call, ordered by position in the audio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "calls"
                ],
                "summary": "Get call transmissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Trunk-recorder call ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response with transmissions array and count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/recorders": {
            "get": {
                "description": "Returns all known recorder states from in-memory cache (populated by MQTT recorder messages)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recorders"
                ],
                "summary": "List recorder states",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.RecorderListResponse"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Returns overall system statistics including counts and call metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get system statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/activity": {
            "get": {
                "description": "Returns summary statistics and recent activity across all systems",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get activity summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ActivityResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/rates": {
            "get": {
                "description": "Returns system decode rate measurements over time",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get decode rates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time filter (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.RatesResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/systems": {
            "get": {
                "description": "Returns all registered radio systems",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "List all systems",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SystemListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/systems/{id}": {
            "get": {
                "description": "Returns a single system by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "Get a system",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "System ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.System"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/systems/{id}/talkgroups": {
            "get": {
                "description": "Returns all talkgroups for a specific system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "List system talkgroups",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "System ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.TalkgroupListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/talkgroups": {
            "get": {
                "description": "Returns all talkgroups, optionally filtered by SYSID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talkgroups"
                ],
                "summary": "List all talkgroups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by SYSID (P25 system identifier)",
                        "name": "sysid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.TalkgroupListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/talkgroups/encryption-stats": {
            "get": {
                "description": "Returns counts of encrypted and clear calls per talkgroup from recent activity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talkgroups"
                ],
                "summary": "Get encryption stats per talkgroup",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Hours of history to include (default 24)",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/talkgroups/{id}": {
            "get": {
                "description": "Returns a single talkgroup. Accepts sysid:tgid format (e.g., \"348:9178\") or plain tgid (returns 409 if ambiguous)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talkgroups"
                ],
                "summary": "Get a talkgroup",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Talkgroup ID (sysid:tgid or plain tgid)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Talkgroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Ambiguous tgid exists in multiple systems",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/talkgroups/{id}/calls": {
            "get": {
                "description": "Returns calls for a specific talkgroup by TGID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "talkgroups"
                ],
                "summary": "List talkgroup calls",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Talkgroup ID (TGID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time filter (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CallListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transcription/status": {
            "get": {
                "description": "Returns statistics about the transcription queue",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transcriptions"
                ],
                "summary": "Get transcription queue status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/database.TranscriptionQueueStats"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transcriptions/recent": {
            "get": {
                "description": "Returns recently created transcriptions with call context",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transcriptions"
                ],
                "summary": "Get recent transcriptions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transcriptions/search": {
            "get": {
                "description": "Full-text search across all transcriptions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transcriptions"
                ],
                "summary": "Search transcriptions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/units": {
            "get": {
                "description": "Returns all radio units, optionally filtered by SYSID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "List all units",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by SYSID (P25 system identifier)",
                        "name": "sysid",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.UnitListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/units/active": {
            "get": {
                "description": "Returns units that have had recent activity within the specified time window",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "List active units",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Activity window in minutes (1-60)",
                        "name": "window",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by SYSID (P25 system identifier)",
                        "name": "sysid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "System ID or short_name (deprecated, use sysid)",
                        "name": "system",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "System short name",
                        "name": "sys_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by talkgroup ID",
                        "name": "talkgroup",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ActiveUnitListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/units/{id}": {
            "get": {
                "description": "Returns a single unit. Accepts sysid:unit_id format (e.g., \"348:1234567\") or plain unit_id (returns 409 if ambiguous across systems)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "Get a unit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unit ID (sysid:unit_id or plain unit_id)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Unit"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Ambiguous unit_id exists in multiple systems",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/units/{id}/calls": {
            "get": {
                "description": "Returns calls that include transmissions from a specific unit by radio ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "List unit calls",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unit radio ID (RID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time filter (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CallListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/units/{id}/events": {
            "get": {
                "description": "Returns events (affiliations, registrations, etc.) for a specific unit by radio ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units"
                ],
                "summary": "List unit events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unit radio ID (RID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by event type (on, off, join, call, etc.)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by talkgroup ID (TGID)",
                        "name": "talkgroup",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time filter (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.UnitEventListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.TranscriptionQueueStats": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "pending": {
                    "type": "integer"
                },
                "processing": {
                    "type": "integer"
                }
            }
        },
        "ingest.RecorderInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "duration": {
                    "type": "number"
                },
                "freq": {
                    "type": "integer"
                },
                "rec_num": {
                    "type": "integer"
                },
                "rec_state_type": {
                    "type": "string"
                },
                "rec_type": {
                    "type": "string"
                },
                "recorder_id": {
                    "type": "integer"
                },
                "squelched": {
                    "type": "boolean"
                },
                "src_num": {
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                },
                "tg_alpha_tag": {
                    "type": "string"
                },
                "tgid": {
                    "type": "integer"
                },
                "unit_alpha_tag": {
                    "type": "string"
                },
                "unit_id": {
                    "type": "integer"
                }
            }
        },
        "models.Call": {
            "description": "A recorded radio call/transmission",
            "type": "object",
            "properties": {
                "analog": {
                    "type": "boolean",
                    "example": false
                },
                "audio_path": {
                    "description": "Audio",
                    "type": "string",
                    "example": "butco/2024/01/15/1001-1705319400.m4a"
                },
                "audio_size": {
                    "type": "integer",
                    "example": 45000
                },
                "audio_type": {
                    "type": "string",
                    "example": "digital"
                },
                "audio_url": {
                    "type": "string",
                    "example": "/api/v1/calls/123/audio"
                },
                "call_group_id": {
                    "type": "integer",
                    "example": 1
                },
                "call_num": {
                    "type": "integer",
                    "example": 12345
                },
                "call_state": {
                    "description": "Status",
                    "type": "integer",
                    "example": 3
                },
                "conventional": {
                    "type": "boolean",
                    "example": false
                },
                "duration": {
                    "type": "number",
                    "example": 45.5
                },
                "emergency": {
                    "type": "boolean",
                    "example": false
                },
                "encrypted": {
                    "type": "boolean",
                    "example": false
                },
                "error_count": {
                    "type": "integer",
                    "example": 2
                },
                "freq": {
                    "description": "Quality",
                    "type": "integer",
                    "example": 851012500
                },
                "freq_error": {
                    "type": "integer",
                    "example": 0
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "instance_id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata_json": {
                    "description": "Metadata",
                    "type": "object"
                },
                "mon_state": {
                    "type": "integer",
                    "example": 0
                },
                "noise_db": {
                    "type": "number",
                    "example": -80
                },
                "patched_tgids": {
                    "description": "Patches",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "phase2_tdma": {
                    "type": "boolean",
                    "example": false
                },
                "recorder_id": {
                    "type": "integer",
                    "example": 1
                },
                "signal_db": {
                    "type": "number",
                    "example": -45.5
                },
                "spike_count": {
                    "type": "integer",
                    "example": 0
                },
                "start_time": {
                    "description": "Timing",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "stop_time": {
                    "type": "string",
                    "example": "2024-01-15T10:30:45Z"
                },
                "system_id": {
                    "type": "integer",
                    "example": 1
                },
                "tdma_slot": {
                    "type": "integer",
                    "example": 0
                },
                "tg_alpha_tag": {
                    "type": "string",
                    "example": "09-8L Main"
                },
                "tg_sysid": {
                    "type": "string",
                    "example": "348"
                },
                "tgid": {
                    "description": "Joined fields (not stored in calls table)",
                    "type": "integer",
                    "example": 9178
                },
                "tr_call_id": {
                    "description": "Identifiers",
                    "type": "string",
                    "example": "butco-1001-1705319400"
                },
                "units": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.CallUnit"
                    }
                }
            }
        },
        "models.CallUnit": {
            "type": "object",
            "properties": {
                "alpha_tag": {
                    "type": "string",
                    "example": "09 7COM3"
                },
                "unit_rid": {
                    "type": "integer",
                    "example": 924003
                }
            }
        },
        "models.System": {
            "description": "A radio system (P25, SmartNet, conventional, etc.)",
            "type": "object",
            "properties": {
                "config_json": {
                    "type": "object"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "instance_id": {
                    "type": "integer",
                    "example": 1
                },
                "nac": {
                    "type": "string",
                    "example": "293"
                },
                "rfss": {
                    "type": "integer",
                    "example": 1
                },
                "short_name": {
                    "type": "string",
                    "example": "butco"
                },
                "site_id": {
                    "type": "integer",
                    "example": 1
                },
                "sys_num": {
                    "type": "integer",
                    "example": 0
                },
                "sysid": {
                    "type": "string",
                    "example": "1234"
                },
                "system_type": {
                    "type": "string",
                    "example": "p25"
                },
                "wacn": {
                    "type": "string",
                    "example": "BEE00"
                }
            }
        },
        "models.Talkgroup": {
            "description": "A talkgroup on a radio system, unique within a SYSID",
            "type": "object",
            "properties": {
                "alpha_tag": {
                    "type": "string",
                    "example": "Fire Dispatch"
                },
                "description": {
                    "type": "string",
                    "example": "County Fire Dispatch Channel"
                },
                "first_seen": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "group": {
                    "type": "string",
                    "example": "Fire"
                },
                "last_seen": {
                    "type": "string",
                    "example": "2024-01-15T12:30:00Z"
                },
                "mode": {
                    "type": "string",
                    "example": "D"
                },
                "priority": {
                    "type": "integer",
                    "example": 1
                },
                "sysid": {
                    "type": "string",
                    "example": "348"
                },
                "tag": {
                    "type": "string",
                    "example": "Fire Dispatch"
                },
                "tgid": {
                    "type": "integer",
                    "example": 1001
                }
            }
        },
        "models.Transcription": {
            "description": "A transcription of a radio call's audio content",
            "type": "object",
            "properties": {
                "call_duration": {
                    "description": "seconds, for word timeline rendering",
                    "type": "number",
                    "example": 15.5
                },
                "call_id": {
                    "type": "integer",
                    "example": 123
                },
                "confidence": {
                    "type": "number",
                    "example": 0.95
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-15T12:30:00Z"
                },
                "duration_ms": {
                    "type": "integer",
                    "example": 1500
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "language": {
                    "type": "string",
                    "example": "en"
                },
                "model": {
                    "type": "string",
                    "example": "whisper-1"
                },
                "provider": {
                    "type": "string",
                    "example": "openai"
                },
                "text": {
                    "type": "string",
                    "example": "Engine 5 responding to the scene"
                },
                "word_count": {
                    "type": "integer",
                    "example": 6
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.TranscriptionWord"
                    }
                }
            }
        },
        "models.TranscriptionWord": {
            "description": "A word from the transcription with start and end times",
            "type": "object",
            "properties": {
                "end": {
                    "description": "seconds from start of audio",
                    "type": "number",
                    "example": 0.85
                },
                "start": {
                    "description": "seconds from start of audio",
                    "type": "number",
                    "example": 0.5
                },
                "word": {
                    "type": "string",
                    "example": "Engine"
                }
            }
        },
        "models.Unit": {
            "description": "A radio unit (mobile or portable radio), unique within a SYSID",
            "type": "object",
            "properties": {
                "alpha_tag": {
                    "type": "string",
                    "example": "Engine 1"
                },
                "alpha_tag_source": {
                    "type": "string",
                    "example": "radioreference"
                },
                "first_seen": {
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "last_event_tg_tag": {
                    "type": "string",
                    "example": "09-8L Main"
                },
                "last_event_tgid": {
                    "type": "integer",
                    "example": 9178
                },
                "last_event_time": {
                    "type": "string"
                },
                "last_event_type": {
                    "description": "Joined fields (not stored in units table)",
                    "type": "string",
                    "example": "call"
                },
                "last_seen": {
                    "type": "string",
                    "example": "2024-01-15T12:30:00Z"
                },
                "sysid": {
                    "type": "string",
                    "example": "348"
                },
                "unit_id": {
                    "type": "integer",
                    "example": 1234567
                }
            }
        },
        "models.UnitEvent": {
            "description": "A unit event such as registration, affiliation, or call activity",
            "type": "object",
            "properties": {
                "event_type": {
                    "type": "string",
                    "example": "join"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "instance_id": {
                    "type": "integer",
                    "example": 1
                },
                "metadata_json": {
                    "type": "object"
                },
                "system_id": {
                    "type": "integer",
                    "example": 1
                },
                "tg_sysid": {
                    "type": "string",
                    "example": "348"
                },
                "tgid": {
                    "type": "integer",
                    "example": 1001
                },
                "time": {
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "unit_rid": {
                    "type": "integer",
                    "example": 1234567
                },
                "unit_sysid": {
                    "type": "string",
                    "example": "348"
                }
            }
        },
        "rest.ActiveUnitListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 10
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "units": {},
                "window": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "rest.ActivityResponse": {
            "type": "object",
            "properties": {
                "calls_24h": {
                    "type": "integer",
                    "example": 5000
                },
                "system_activity": {},
                "systems": {
                    "type": "integer",
                    "example": 3
                },
                "talkgroups": {
                    "type": "integer",
                    "example": 500
                },
                "units": {
                    "type": "integer",
                    "example": 1000
                }
            }
        },
        "rest.CallGroupDetailResponse": {
            "type": "object",
            "properties": {
                "call_group": {},
                "calls": {}
            }
        },
        "rest.CallGroupListResponse": {
            "type": "object",
            "properties": {
                "call_groups": {},
                "count": {
                    "type": "integer",
                    "example": 50
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "rest.CallListResponse": {
            "type": "object",
            "properties": {
                "calls": {},
                "count": {
                    "type": "integer",
                    "example": 25
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "rest.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Resource not found"
                }
            }
        },
        "rest.RatesResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 100
                },
                "rates": {}
            }
        },
        "rest.RecorderListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 12
                },
                "recorders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ingest.RecorderInfo"
                    }
                }
            }
        },
        "rest.SystemListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "systems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.System"
                    }
                }
            }
        },
        "rest.TalkgroupListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 100
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "talkgroups": {}
            }
        },
        "rest.TranscribeCallRequest": {
            "type": "object",
            "properties": {
                "priority": {
                    "type": "integer"
                }
            }
        },
        "rest.UnitEventListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 100
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UnitEvent"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "rest.UnitListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 50
                },
                "limit": {
                    "type": "integer",
                    "example": 50
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "units": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Unit"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Radio system operations",
            "name": "systems"
        },
        {
            "description": "Talkgroup operations",
            "name": "talkgroups"
        },
        {
            "description": "Radio unit operations",
            "name": "units"
        },
        {
            "description": "Call recording operations",
            "name": "calls"
        },
        {
            "description": "Deduplicated call group operations",
            "name": "call-groups"
        },
        {
            "description": "Statistics and activity operations",
            "name": "stats"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.2-beta1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "tr-engine API",
	Description:      "Backend service for trunk-recorder data ingestion and querying. Provides REST APIs for accessing radio system data, calls, talkgroups, and units.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
